### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by kaelZ** [gangstead/atom-scala-format#3]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.

```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:55:11)
Object.activate (/home/kael/.atom/packages/scala-format/lib/scala-format.js:20:21)
```

**Comment by gangstead** [comment]
Fixed in 0.1.3 with Atom 0.181 or above.
